### ISSUE TITLE
Make this project a work with DUB?

### ISSUE THREAD

**Issue by dariusc93** [MikeWey/DMagick#12]
Hi,

I would like to know if you have plans on using dub to distribute this and make it easier for developers to implement this into their application.

**Comment by r4j4h** [comment]
Reference: https://github.com/etcimon/DMagick/commit/cdac2c86fa4fac6a5e6864c06e77d103e1de9b0a

**Comment by aberba** [comment]
Yeah getting it to use dub will be great

**Comment by MikeWey** [comment]
http://code.dlang.org/packages/dmagick
