### ISSUE TITLE
zero-length blob not permitted 

### ISSUE THREAD

**Issue by donglei** [MikeWey/DMagick#15]
DMgaick throw exception with message :  
zero-length blob not permitted `' @ error/blob.c/BlobToImage/346 line:2398 file:source/dmagick/Image.d

how can I fixed it! thanks

**Comment by MikeWey** [comment]
ImageMagick doesn't support empty blobs, so no this can't be fixed.

**Comment by donglei** [comment]
Thanks, I know how to fixed, check blobs is empty or not before call ImageMagick
