### ISSUE TITLE
set image quality does not work 

### ISSUE THREAD

**Issue by donglei** [MikeWey/DMagick#17]
auto originalIMage = new Image(blob);
.....
originalIMage.resize(........);
originalIMage.quality(65);
originalIMage.toBlob();

but image quality does not work?
how can i do that?

**Comment by MikeWey** [comment]
The following is working for me, do you have a more complete example that's not working?

``` D
Image example = new Image(Geometry(100, 100), new Color("green"));
example.quality = 60;
void[] blob = example.toBlob("jpg");

Image test = new Image(blob);
assert(test.quality == 60);
```

**Comment by donglei** [comment]
<pre><code>
import std.stdio;

void main()
{
	import dmagick.Image;
	auto img = new Image("./007c6581e43b86f1676ed5762ddac3362d460605.jpeg");
	img.quality(10);
	img.write("./test.png");
	
}
</code></pre>
the test.png does not smaller than 007c6581e43b86f1676ed5762ddac3362d460605.jpeg.
it just has property with quality = 10, but looks like the original, without the effect of the fuzzy

**Comment by donglei** [comment]
maybe it cased by png formate
