### ISSUE TITLE
Image procesing programmatically

### ISSUE THREAD

**Issue by aberba** [MikeWey/DMagick#20]
Does it currently support  image processing functions like scaling, conversion and reducing quality programatically (uisng the API)?

**Comment by MikeWey** [comment]
Some of the newer functionality might not be available on the D side but those thins should be available.

For example for resizing:
http://dmagick.mikewey.eu/docs/Image.html#liquidRescale
http://dmagick.mikewey.eu/docs/Image.html#resize
http://dmagick.mikewey.eu/docs/Image.html#scale
